from datetime import datetime
from typing import Any, Dict
from google.genai import types
from memory import (
    build_evidence_context,
    get_session_context,
    save_evidence,
    save_last_user_query,
)
from worker_agents import (
    retriever_agent,
    run_model,
    verifier_agent,
    writer_agent,
)
"""
Orchestrator
=====================================================================================
In the orchestrator tool schema there are 4 tools defined:
3 agentic tools: (Retriever, Writer and Verifier).
and 1 non agentic tool(reuse_cached_evidence)

1. reuse_cached_evidence is used when there is stored evidence in memory
relevant to the current query. It prevents retrieving information that
has already been gathered for a similar query. It is a non-agent tool.

2. call_retriever_agent is the worker agent to retrieve information from a set of
documents or the web or both depending on the query.

3. call_writer_agent is the worker agent to write a report based on what was retrieved
from the retriever agent.
4. call_verifier_agent is the worker agent to verify the claims in the content generated by the writer agent
and return the final report.

Depending on the query the orchestrator can reuse stored evidence from memory if
relevant information is already available, or retrieve evidence first and then
proceed to writing and verification.
"""

# Tool schema used by the orchestrator to coordinate worker agents.
ORCHESTRATOR_TOOL_SCHEMAS = types.Tool(
    function_declarations=[
        types.FunctionDeclaration(
            name="reuse_cached_evidence",
            description=(
                """Activate the cached evidence from the previous turn when it is still
                clearly and directly relevant to the current query. Prefer this for
                follow-up questions that rely on the same evidence. Do not use it when
                the user asks for a different detail, angle, missing information, or a
                new topic."""
            ),
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "reason": {
                        "type": "string",
                        "description": "Short explanation of why the cached evidence is still directly relevant.",
                    }
                },
                "required": ["reason"],
            },
        ),
        types.FunctionDeclaration(
            name="call_retriever_agent",
            description=(
                """Gather evidence for the current query. Use this for evidence-request
                turns when cached evidence is missing, not clearly relevant, or the
                user asks for a different detail, angle, or missing information. This
                worker decides whether to use uploaded documents, web search, or both."""
            ),
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Self-contained evidence request for the retriever. Rewrite follow-up questions to include omitted subject details when needed.",
                    }
                },
                "required": ["query"],
            },
        ),
        types.FunctionDeclaration(
            name="call_writer_agent",
            description=(
                """Write the report using the active retrieved evidence. Use only after
                evidence has been activated for the current turn."""
            ),
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "user_query": {
                        "type": "string",
                        "description": "The current user request to answer.",
                    },
                    "evidence_text": {
                        "type": "string",
                        "description": "The active formatted evidence to ground the draft.",
                    },
                },
                "required": ["user_query", "evidence_text"],
            },
        ),
        types.FunctionDeclaration(
            name="call_verifier_agent",
            description=(
                """Verify whether the report draft is grounded in the active evidence and
                return the final report. Use only after a writer draft exists and
                evidence is active for the current turn."""
            ),
            parameters_json_schema={
                "type": "object",
                "properties": {
                    "written_draft": {
                        "type": "string",
                        "description": "The writer agent's draft to verify.",
                    },
                    "evidence_text": {
                        "type": "string",
                        "description": "The active formatted evidence used to check the draft.",
                    },
                },
                "required": ["written_draft", "evidence_text"],
            },
        ),
    ]
)

# Instructions guiding the LLM's behavior in Orchestrator
ORCHESTRATOR_INSTRUCTIONS = (
    f"""
    You coordinate three worker agents: retriever, writer, and verifier.

    Classify each user turn as one of:
    1. social:
    greetings, thanks, acknowledgements, brief conversational turns, or closing messages.
    Examples: "hello", "hi", "thanks", "ok", "bye", "great"

    2. out_of_scope:
    requests that are not document or web research tasks.
    Examples: coding help, simple math, or unrelated general tasks.

    3. evidence_request:
    factual or research-style questions that should be answered using evidence from the uploaded documents, the web, or both.
    Use this for questions about the active PDFs, named topics, concepts, models, papers, products, companies, people, or current events, and for explicit web-search requests.

    Rules:
    - If social, reply naturally in one short sentence and do not call any tools.
    - If out_of_scope, do not answer the request and do not call any tools.
    - For out_of_scope, reply briefly: "I'm a research assistant focused on answering questions about the active documents and on researching the web when needed."
    - Treat factual questions about named topics, concepts, models, products, papers, or companies as evidence_request.
    - If a question could plausibly be answered from the active PDFs or from web research, prefer evidence_request over out_of_scope.
    - Only use call_retriever_agent for evidence_request turns.
    - For evidence_request turns, choose the next valid tool based on the current state.
    - Activate evidence before writing, and write before verifying.
    - Return the verifier output when available.
    """
)
ORCHESTRATOR_MODEL = "gemini-2.5-flash"
ORCHESTRATOR_THINKING_BUDGET = 0

# Format the current orchestration state for the model.
def build_orchestrator_prompt_context(state: dict[str, Any]) -> str:
    evidence_context = build_evidence_context(state["evidence_json"])
    return (
        f"- current_date: {state['current_date']}\n"
        f"- last_user_query: {state['last_user_query'] or 'None'}\n"
        f"- cached_query: {state['cached_query'] or 'None'}\n"
        f"- retrieval_attempted: {state['retrieval_attempted']}\n"
        f"- has_written_draft: {bool(state['written_draft'])}\n"
        f"- has_verification: {bool(state['verification'])}\n\n"
        f"Cached evidence summary:\n{state['cached_evidence_summary']}\n\n"
        f"Current evidence summary:\n{evidence_context['summary']}"
    )

"""
Helper memory handler functions used in the Orchestrator
=====================================================================
For a given session id in the orchestrator the memory helper functions work like this:

- save_evidence: saves the latest retrieved evidence for the session so it can
be reused for followup questions when still relevant.

- save_last_user_query: saves the latest user query for followup questions.

- build_evidence_context: parses saved evidence_json and returns a summary evidence status, and formatted evidence.
- get_session_context: returns the latest user query and cached evidence
- context for the session to support followup questions and evidence reuse.
"""

def orchestrator_agent(
    user_query: str,
    session_id: str = "default",
    verbose: bool = True,
) -> Dict[str, Any]:

    # Load session context for follow-up questions and cached evidence reuse.
    session_context = get_session_context(session_id)
    cached_evidence_json = session_context["cached_evidence_json"]

    # Current date to support time-aware decisions.
    current_date = datetime.now().astimezone().date().isoformat()

    state = {
        "user_query": user_query,
        "current_date": current_date,
        "last_user_query": session_context["last_user_query"],
        "cached_query": session_context["cached_query"],
        "cached_evidence_summary": session_context["cached_evidence_summary"],
        "retrieval_attempted": False,
        "evidence_json": "",
        "written_draft": "",
        "verification": "",
        "final_answer": "",
    }
    evidence_already_active = "Evidence is already active for this turn; proceed to writing."

    # Caller-owned conversation history. Gemini has no server-side
    # equivalent of OpenAI's previous_response_id, so every round must
    # be appended here and sent in full on the next call.
    contents = [
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(
                    text=(
                        f"User query: {user_query}\n\n"
                        f"Current state:\n{build_orchestrator_prompt_context(state)}"
                    )
                )
            ],
        )
    ]

    response = run_model(
        instructions=ORCHESTRATOR_INSTRUCTIONS,
        model=ORCHESTRATOR_MODEL,
        thinking_budget=ORCHESTRATOR_THINKING_BUDGET,
        contents=contents,
        tools=[ORCHESTRATOR_TOOL_SCHEMAS],
    )

    # Allow up to 4 orchestration rounds before stopping.
    for _ in range(4):
        function_calls = response.function_calls

        # If the model does not request any tools, return its direct reply.
        if not function_calls:
            state["final_answer"] = response.text or "I couldn't find enough evidence to answer that."
            save_last_user_query(session_id, user_query)
            return state

        # Carry the model's own turn (including its function-call parts)
        # forward before appending the function-response turn.
        contents.append(response.candidates[0].content)

        function_response_parts = []

        for call in function_calls:
            name = call.name
            args = call.args

            if name == "reuse_cached_evidence":
                if state["evidence_json"]:
                    output = evidence_already_active
                elif cached_evidence_json:
                    if verbose:
                        print("[ORCHESTRATOR] Reusing cached evidence.")
                    state["evidence_json"] = cached_evidence_json
                    state["cached_query"] = session_context["cached_query"]
                    output = f"Reused cached evidence: {args['reason']}"
                else:
                    output = "No cached evidence is available to reuse."

            elif name == "call_retriever_agent":
                if state["evidence_json"]:
                    output = evidence_already_active
                elif state["retrieval_attempted"]:
                    output = "Retrieval has already been attempted for this turn."
                else:
                    state["retrieval_attempted"] = True
                    if verbose:
                        print("[ORCHESTRATOR] Initializing Retriever Agent...")
                    evidence_pack = retriever_agent(
                        args["query"].strip() or state["user_query"],
                        last_user_query=state["last_user_query"],
                        verbose=verbose,
                    )
                    output = evidence_pack.model_dump_json()
                    evidence_context = build_evidence_context(output)
                    if evidence_context["has_evidence"]:
                        state["evidence_json"] = output
                        state["cached_query"] = state["user_query"]
                        # save retrieved evidence
                        save_evidence(session_id, state["user_query"], output)
                        state["cached_evidence_summary"] = evidence_context["summary"]
                    else:
                        output = evidence_pack.summary or "Retriever could not gather enough evidence."

            elif name in {"call_writer_agent", "call_verifier_agent"}:
                evidence_context = build_evidence_context(
                    state["evidence_json"],
                    include_formatted_evidence=True,
                )
                formatted_evidence = evidence_context["formatted_evidence"]
                if name == "call_writer_agent":
                    if not formatted_evidence:
                        output = "Cannot write yet because no retrieval evidence has been activated."
                    else:
                        if verbose:
                            print("[ORCHESTRATOR] Initializing Writer Agent...")
                        output = writer_agent(
                            user_query=state["user_query"],
                            evidence_text=formatted_evidence,
                            verbose=verbose,
                        )
                        state["written_draft"] = output
                elif not state["written_draft"]:
                    output = "Cannot verify yet because no report draft exists."
                elif not formatted_evidence:
                    output = "Cannot verify yet because no retrieval evidence is active."
                else:
                    if verbose:
                        print("[ORCHESTRATOR] Initializing Verifier Agent...")
                    output = verifier_agent(
                        user_query=state["user_query"],
                        written_draft=state["written_draft"],
                        evidence_text=formatted_evidence,
                        verbose=verbose,
                    )
                    state["verification"] = output

            else:
                output = "Unknown tool name."

            function_response_parts.append(
                types.Part.from_function_response(name=name, response={"result": output})
            )

        # Finalize as soon as verification is in hand instead of spending
        # another round asking the model to relay it back: that extra
        # round-trip risks the model paraphrasing or blending in the
        # writer's draft rather than returning the verifier output verbatim.
        if state["verification"]:
            state["final_answer"] = state["verification"]
            save_last_user_query(session_id, user_query)
            return state

        function_response_parts.append(
            types.Part.from_text(text=f"Updated state:\n{build_orchestrator_prompt_context(state)}")
        )
        contents.append(types.Content(role="user", parts=function_response_parts))

        response = run_model(
            instructions=ORCHESTRATOR_INSTRUCTIONS,
            model=ORCHESTRATOR_MODEL,
            thinking_budget=ORCHESTRATOR_THINKING_BUDGET,
            contents=contents,
            tools=[ORCHESTRATOR_TOOL_SCHEMAS],
        )

    if state["verification"]:
        state["final_answer"] = state["verification"]
        save_last_user_query(session_id, user_query)
    else:
        state["final_answer"] = "Stopped because the maximum number of orchestration steps was reached."

    if verbose:
        print("[ORCHESTRATOR] Workflow complete.")
    return state
